# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nathan/epitech_project/OOP_indie_studio_2018

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nathan/epitech_project/OOP_indie_studio_2018

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nathan/epitech_project/OOP_indie_studio_2018/CMakeFiles /home/nathan/epitech_project/OOP_indie_studio_2018/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nathan/epitech_project/OOP_indie_studio_2018/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bomberman

# Build rule for target.
bomberman: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bomberman
.PHONY : bomberman

# fast build rule for target.
bomberman/fast:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/build
.PHONY : bomberman/fast

src/Main.o: src/Main.cpp.o

.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i

.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s

.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/engine/ISGE.o: src/engine/ISGE.cpp.o

.PHONY : src/engine/ISGE.o

# target to build an object file
src/engine/ISGE.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/engine/ISGE.cpp.o
.PHONY : src/engine/ISGE.cpp.o

src/engine/ISGE.i: src/engine/ISGE.cpp.i

.PHONY : src/engine/ISGE.i

# target to preprocess a source file
src/engine/ISGE.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/engine/ISGE.cpp.i
.PHONY : src/engine/ISGE.cpp.i

src/engine/ISGE.s: src/engine/ISGE.cpp.s

.PHONY : src/engine/ISGE.s

# target to generate assembly for a file
src/engine/ISGE.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/engine/ISGE.cpp.s
.PHONY : src/engine/ISGE.cpp.s

src/game/Alphabet.o: src/game/Alphabet.cpp.o

.PHONY : src/game/Alphabet.o

# target to build an object file
src/game/Alphabet.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/game/Alphabet.cpp.o
.PHONY : src/game/Alphabet.cpp.o

src/game/Alphabet.i: src/game/Alphabet.cpp.i

.PHONY : src/game/Alphabet.i

# target to preprocess a source file
src/game/Alphabet.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/game/Alphabet.cpp.i
.PHONY : src/game/Alphabet.cpp.i

src/game/Alphabet.s: src/game/Alphabet.cpp.s

.PHONY : src/game/Alphabet.s

# target to generate assembly for a file
src/game/Alphabet.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/game/Alphabet.cpp.s
.PHONY : src/game/Alphabet.cpp.s

src/game/Bomb.o: src/game/Bomb.cpp.o

.PHONY : src/game/Bomb.o

# target to build an object file
src/game/Bomb.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/game/Bomb.cpp.o
.PHONY : src/game/Bomb.cpp.o

src/game/Bomb.i: src/game/Bomb.cpp.i

.PHONY : src/game/Bomb.i

# target to preprocess a source file
src/game/Bomb.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/game/Bomb.cpp.i
.PHONY : src/game/Bomb.cpp.i

src/game/Bomb.s: src/game/Bomb.cpp.s

.PHONY : src/game/Bomb.s

# target to generate assembly for a file
src/game/Bomb.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/game/Bomb.cpp.s
.PHONY : src/game/Bomb.cpp.s

src/game/Bomberman.o: src/game/Bomberman.cpp.o

.PHONY : src/game/Bomberman.o

# target to build an object file
src/game/Bomberman.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/game/Bomberman.cpp.o
.PHONY : src/game/Bomberman.cpp.o

src/game/Bomberman.i: src/game/Bomberman.cpp.i

.PHONY : src/game/Bomberman.i

# target to preprocess a source file
src/game/Bomberman.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/game/Bomberman.cpp.i
.PHONY : src/game/Bomberman.cpp.i

src/game/Bomberman.s: src/game/Bomberman.cpp.s

.PHONY : src/game/Bomberman.s

# target to generate assembly for a file
src/game/Bomberman.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/game/Bomberman.cpp.s
.PHONY : src/game/Bomberman.cpp.s

src/game/Flame.o: src/game/Flame.cpp.o

.PHONY : src/game/Flame.o

# target to build an object file
src/game/Flame.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/game/Flame.cpp.o
.PHONY : src/game/Flame.cpp.o

src/game/Flame.i: src/game/Flame.cpp.i

.PHONY : src/game/Flame.i

# target to preprocess a source file
src/game/Flame.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/game/Flame.cpp.i
.PHONY : src/game/Flame.cpp.i

src/game/Flame.s: src/game/Flame.cpp.s

.PHONY : src/game/Flame.s

# target to generate assembly for a file
src/game/Flame.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/game/Flame.cpp.s
.PHONY : src/game/Flame.cpp.s

src/game/Game.o: src/game/Game.cpp.o

.PHONY : src/game/Game.o

# target to build an object file
src/game/Game.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/game/Game.cpp.o
.PHONY : src/game/Game.cpp.o

src/game/Game.i: src/game/Game.cpp.i

.PHONY : src/game/Game.i

# target to preprocess a source file
src/game/Game.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/game/Game.cpp.i
.PHONY : src/game/Game.cpp.i

src/game/Game.s: src/game/Game.cpp.s

.PHONY : src/game/Game.s

# target to generate assembly for a file
src/game/Game.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/game/Game.cpp.s
.PHONY : src/game/Game.cpp.s

src/game/GameOverTransition.o: src/game/GameOverTransition.cpp.o

.PHONY : src/game/GameOverTransition.o

# target to build an object file
src/game/GameOverTransition.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/game/GameOverTransition.cpp.o
.PHONY : src/game/GameOverTransition.cpp.o

src/game/GameOverTransition.i: src/game/GameOverTransition.cpp.i

.PHONY : src/game/GameOverTransition.i

# target to preprocess a source file
src/game/GameOverTransition.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/game/GameOverTransition.cpp.i
.PHONY : src/game/GameOverTransition.cpp.i

src/game/GameOverTransition.s: src/game/GameOverTransition.cpp.s

.PHONY : src/game/GameOverTransition.s

# target to generate assembly for a file
src/game/GameOverTransition.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/game/GameOverTransition.cpp.s
.PHONY : src/game/GameOverTransition.cpp.s

src/game/GameTransition.o: src/game/GameTransition.cpp.o

.PHONY : src/game/GameTransition.o

# target to build an object file
src/game/GameTransition.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/game/GameTransition.cpp.o
.PHONY : src/game/GameTransition.cpp.o

src/game/GameTransition.i: src/game/GameTransition.cpp.i

.PHONY : src/game/GameTransition.i

# target to preprocess a source file
src/game/GameTransition.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/game/GameTransition.cpp.i
.PHONY : src/game/GameTransition.cpp.i

src/game/GameTransition.s: src/game/GameTransition.cpp.s

.PHONY : src/game/GameTransition.s

# target to generate assembly for a file
src/game/GameTransition.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/game/GameTransition.cpp.s
.PHONY : src/game/GameTransition.cpp.s

src/game/MainMenu.o: src/game/MainMenu.cpp.o

.PHONY : src/game/MainMenu.o

# target to build an object file
src/game/MainMenu.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/game/MainMenu.cpp.o
.PHONY : src/game/MainMenu.cpp.o

src/game/MainMenu.i: src/game/MainMenu.cpp.i

.PHONY : src/game/MainMenu.i

# target to preprocess a source file
src/game/MainMenu.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/game/MainMenu.cpp.i
.PHONY : src/game/MainMenu.cpp.i

src/game/MainMenu.s: src/game/MainMenu.cpp.s

.PHONY : src/game/MainMenu.s

# target to generate assembly for a file
src/game/MainMenu.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/game/MainMenu.cpp.s
.PHONY : src/game/MainMenu.cpp.s

src/game/Map.o: src/game/Map.cpp.o

.PHONY : src/game/Map.o

# target to build an object file
src/game/Map.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/game/Map.cpp.o
.PHONY : src/game/Map.cpp.o

src/game/Map.i: src/game/Map.cpp.i

.PHONY : src/game/Map.i

# target to preprocess a source file
src/game/Map.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/game/Map.cpp.i
.PHONY : src/game/Map.cpp.i

src/game/Map.s: src/game/Map.cpp.s

.PHONY : src/game/Map.s

# target to generate assembly for a file
src/game/Map.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/game/Map.cpp.s
.PHONY : src/game/Map.cpp.s

src/game/Player.o: src/game/Player.cpp.o

.PHONY : src/game/Player.o

# target to build an object file
src/game/Player.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/game/Player.cpp.o
.PHONY : src/game/Player.cpp.o

src/game/Player.i: src/game/Player.cpp.i

.PHONY : src/game/Player.i

# target to preprocess a source file
src/game/Player.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/game/Player.cpp.i
.PHONY : src/game/Player.cpp.i

src/game/Player.s: src/game/Player.cpp.s

.PHONY : src/game/Player.s

# target to generate assembly for a file
src/game/Player.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/game/Player.cpp.s
.PHONY : src/game/Player.cpp.s

src/game/SoundMenu.o: src/game/SoundMenu.cpp.o

.PHONY : src/game/SoundMenu.o

# target to build an object file
src/game/SoundMenu.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/game/SoundMenu.cpp.o
.PHONY : src/game/SoundMenu.cpp.o

src/game/SoundMenu.i: src/game/SoundMenu.cpp.i

.PHONY : src/game/SoundMenu.i

# target to preprocess a source file
src/game/SoundMenu.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/game/SoundMenu.cpp.i
.PHONY : src/game/SoundMenu.cpp.i

src/game/SoundMenu.s: src/game/SoundMenu.cpp.s

.PHONY : src/game/SoundMenu.s

# target to generate assembly for a file
src/game/SoundMenu.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/game/SoundMenu.cpp.s
.PHONY : src/game/SoundMenu.cpp.s

src/misc_utils/Logger.o: src/misc_utils/Logger.cpp.o

.PHONY : src/misc_utils/Logger.o

# target to build an object file
src/misc_utils/Logger.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/misc_utils/Logger.cpp.o
.PHONY : src/misc_utils/Logger.cpp.o

src/misc_utils/Logger.i: src/misc_utils/Logger.cpp.i

.PHONY : src/misc_utils/Logger.i

# target to preprocess a source file
src/misc_utils/Logger.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/misc_utils/Logger.cpp.i
.PHONY : src/misc_utils/Logger.cpp.i

src/misc_utils/Logger.s: src/misc_utils/Logger.cpp.s

.PHONY : src/misc_utils/Logger.s

# target to generate assembly for a file
src/misc_utils/Logger.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/misc_utils/Logger.cpp.s
.PHONY : src/misc_utils/Logger.cpp.s

src/misc_utils/String.o: src/misc_utils/String.cpp.o

.PHONY : src/misc_utils/String.o

# target to build an object file
src/misc_utils/String.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/misc_utils/String.cpp.o
.PHONY : src/misc_utils/String.cpp.o

src/misc_utils/String.i: src/misc_utils/String.cpp.i

.PHONY : src/misc_utils/String.i

# target to preprocess a source file
src/misc_utils/String.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/misc_utils/String.cpp.i
.PHONY : src/misc_utils/String.cpp.i

src/misc_utils/String.s: src/misc_utils/String.cpp.s

.PHONY : src/misc_utils/String.s

# target to generate assembly for a file
src/misc_utils/String.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/src/misc_utils/String.cpp.s
.PHONY : src/misc_utils/String.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... bomberman"
	@echo "... edit_cache"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/engine/ISGE.o"
	@echo "... src/engine/ISGE.i"
	@echo "... src/engine/ISGE.s"
	@echo "... src/game/Alphabet.o"
	@echo "... src/game/Alphabet.i"
	@echo "... src/game/Alphabet.s"
	@echo "... src/game/Bomb.o"
	@echo "... src/game/Bomb.i"
	@echo "... src/game/Bomb.s"
	@echo "... src/game/Bomberman.o"
	@echo "... src/game/Bomberman.i"
	@echo "... src/game/Bomberman.s"
	@echo "... src/game/Flame.o"
	@echo "... src/game/Flame.i"
	@echo "... src/game/Flame.s"
	@echo "... src/game/Game.o"
	@echo "... src/game/Game.i"
	@echo "... src/game/Game.s"
	@echo "... src/game/GameOverTransition.o"
	@echo "... src/game/GameOverTransition.i"
	@echo "... src/game/GameOverTransition.s"
	@echo "... src/game/GameTransition.o"
	@echo "... src/game/GameTransition.i"
	@echo "... src/game/GameTransition.s"
	@echo "... src/game/MainMenu.o"
	@echo "... src/game/MainMenu.i"
	@echo "... src/game/MainMenu.s"
	@echo "... src/game/Map.o"
	@echo "... src/game/Map.i"
	@echo "... src/game/Map.s"
	@echo "... src/game/Player.o"
	@echo "... src/game/Player.i"
	@echo "... src/game/Player.s"
	@echo "... src/game/SoundMenu.o"
	@echo "... src/game/SoundMenu.i"
	@echo "... src/game/SoundMenu.s"
	@echo "... src/misc_utils/Logger.o"
	@echo "... src/misc_utils/Logger.i"
	@echo "... src/misc_utils/Logger.s"
	@echo "... src/misc_utils/String.o"
	@echo "... src/misc_utils/String.i"
	@echo "... src/misc_utils/String.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

